
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David Soto y Esteban Cabrera
 */
public class GUI_Tanques extends javax.swing.JFrame {
    //Atributos
    private Control ctrl; 
    private Tanque utilizando;
    private int posicionamiento;
    /**
     * Creates new form GUI_Tanques
     */
    public GUI_Tanques() {
        initComponents();
        ctrl = new Control();
        posicionamiento = 0;
        //utilizando = new Tanque();
        RellenarTanque.setEnabled(false);
        Utilizar.setEnabled(false);
        MostrarTanques.setEnabled(false);
        CalcularCantidadCilindricas.setEnabled(false);
        AguaRegion.setEnabled(false);
        
    }
    public void deshabilitar(){
        Abrir1.setEnabled(false);
        Abrir2.setEnabled(false);
        Abrir3.setEnabled(false);
        Abrir4.setEnabled(false);
        Abrir5.setEnabled(false);
        Abrir6.setEnabled(false);
        Abrir7.setEnabled(false);
        Abrir8.setEnabled(false);
        Abrir9.setEnabled(false);
        Abrir10.setEnabled(false);
        Utilizar.setEnabled(false);
    }
    public void habilitar(){
        Abrir1.setEnabled(true);
        Abrir2.setEnabled(true);
        Abrir3.setEnabled(true);
        Abrir4.setEnabled(true);
        Abrir5.setEnabled(true);
        Abrir6.setEnabled(true);
        Abrir7.setEnabled(true);
        Abrir8.setEnabled(true);
        Abrir9.setEnabled(true);
        Abrir10.setEnabled(true);
        Utilizar.setEnabled(true);
    }
    public void abrir(int posicion){
        String ide = TanquesIngresados.getSelectedItem().toString();
        posicionamiento = ctrl.buscarTanque1(ide);
        utilizando = ctrl.buscarTanque(ide);
        String fecha = dia.getValue().toString()+"/"+mes.getValue().toString()+"/"+anio.getValue().toString();
        utilizando.abrirValvula(posicion,fecha);
        ctrl.reingresarTanque(posicionamiento, utilizando);
        double porcentaje = utilizando.calcularPorcentajeAgua();
        String alarma = ctrl.Alerta(porcentaje);
        Advertencia.setText(alarma);
        Advertencia.setEnabled(true);
        RellenarTanque.setEnabled(true);
        if(alarma.equals("ALERTA: Menos de 10% Agua, Valvulas cerradas ")){
            deshabilitar();
        }
    }
    public void cerrar(int posicion){
        String ide = TanquesIngresados.getSelectedItem().toString();
        posicionamiento = ctrl.buscarTanque1(ide);
        utilizando = ctrl.buscarTanque(ide);
        String fecha = dia.getValue().toString()+"/"+mes.getValue().toString()+"/"+anio.getValue().toString();
        utilizando.cerrarValvula(posicion,fecha);
        ctrl.reingresarTanque(posicionamiento, utilizando);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        IDTanque = new javax.swing.JTextField();
        Forma = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Municipio1 = new javax.swing.JTextField();
        Municipio2 = new javax.swing.JTextField();
        Municipio3 = new javax.swing.JTextField();
        Municipio4 = new javax.swing.JTextField();
        Municipio5 = new javax.swing.JTextField();
        Municipio6 = new javax.swing.JTextField();
        Municipio7 = new javax.swing.JTextField();
        Municipio8 = new javax.swing.JTextField();
        Municipio9 = new javax.swing.JTextField();
        Municipio10 = new javax.swing.JTextField();
        IngresarTanque = new javax.swing.JButton();
        Largo = new javax.swing.JSpinner();
        Profundidad = new javax.swing.JSpinner();
        Ancho = new javax.swing.JSpinner();
        Radio = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        Titulo2 = new javax.swing.JLabel();
        TanquesIngresados = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dia = new javax.swing.JSpinner();
        mes = new javax.swing.JSpinner();
        anio = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ShowMuni1 = new javax.swing.JLabel();
        ShowMuni2 = new javax.swing.JLabel();
        ShowMuni3 = new javax.swing.JLabel();
        ShowMuni4 = new javax.swing.JLabel();
        ShowMuni5 = new javax.swing.JLabel();
        ShowMuni6 = new javax.swing.JLabel();
        ShowMuni7 = new javax.swing.JLabel();
        ShowMuni8 = new javax.swing.JLabel();
        ShowMuni9 = new javax.swing.JLabel();
        ShowMuni10 = new javax.swing.JLabel();
        Abrir1 = new javax.swing.JButton();
        Cerrar1 = new javax.swing.JButton();
        Abrir2 = new javax.swing.JButton();
        Cerrar2 = new javax.swing.JButton();
        Abrir3 = new javax.swing.JButton();
        Cerrar3 = new javax.swing.JButton();
        Abrir4 = new javax.swing.JButton();
        Abrir5 = new javax.swing.JButton();
        Abrir6 = new javax.swing.JButton();
        Abrir7 = new javax.swing.JButton();
        Abrir8 = new javax.swing.JButton();
        Abrir9 = new javax.swing.JButton();
        Abrir10 = new javax.swing.JButton();
        Cerrar4 = new javax.swing.JButton();
        Cerrar5 = new javax.swing.JButton();
        Cerrar6 = new javax.swing.JButton();
        Cerrar7 = new javax.swing.JButton();
        Cerrar8 = new javax.swing.JButton();
        Cerrar9 = new javax.swing.JButton();
        Cerrar10 = new javax.swing.JButton();
        Advertencia = new javax.swing.JLabel();
        RellenarTanque = new javax.swing.JButton();
        Utilizar = new javax.swing.JButton();
        Cambiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MostrarTanques = new javax.swing.JButton();
        CalcularCantidadCilindricas = new javax.swing.JButton();
        AguaRegion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Titulo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Titulo1.setText("Ingresar Nuevo Tanque");

        ID.setText("ID Tanque:");

        IDTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTanqueActionPerformed(evt);
            }
        });

        Forma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cilindrico", "Cubico", "Ortogonal" }));
        Forma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormaActionPerformed(evt);
            }
        });

        jLabel2.setText("Forma del Tanque:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Ingrese las medidas necesarias (metros):");

        jLabel4.setText("Largo:");

        jLabel5.setText("Ancho:");

        jLabel6.setText("Profundidad:");

        jLabel7.setText("Radio:");

        jLabel8.setText("Municipio de Valvula 1:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Ingrese los municipios a los que correspondera cada valvula");

        jLabel10.setText("Municipio de Valvula 2:");

        jLabel11.setText("Municipio de Valvula 3:");

        jLabel12.setText("Municipio de Valvula 4:");

        jLabel13.setText("Municipio de Valvula 5:");

        jLabel14.setText("Municipio de Valvula 6:");

        jLabel15.setText("Municipio de Valvula 7:");

        jLabel16.setText("Municipio de Valvula 8:");

        jLabel17.setText("Municipio de Valvula 9:");

        jLabel18.setText("Municipio de Valvula 10:");

        IngresarTanque.setText("Ingresar Tanque");
        IngresarTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarTanqueActionPerformed(evt);
            }
        });

        Largo.setModel(new javax.swing.SpinnerNumberModel(10, 10, 500, 25));

        Profundidad.setModel(new javax.swing.SpinnerNumberModel(10, 10, 500, 25));

        Ancho.setModel(new javax.swing.SpinnerNumberModel(10, 10, 500, 25));

        Radio.setModel(new javax.swing.SpinnerNumberModel(10, 10, 500, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(Titulo1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(Profundidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IDTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(Forma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Largo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(Ancho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Radio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)))))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Municipio9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Municipio10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Municipio7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Municipio8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Municipio5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Municipio6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Municipio4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Municipio3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Municipio1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Municipio2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(IngresarTanque)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(IDTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Forma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(Largo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ancho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(Profundidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Radio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Municipio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Municipio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Municipio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Municipio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Municipio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Municipio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Municipio7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Municipio8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Municipio9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Municipio10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(IngresarTanque)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Titulo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Titulo2.setText("Consulta de Tanque");

        TanquesIngresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanquesIngresadosActionPerformed(evt);
            }
        });

        jLabel21.setText("Codigo de Tanque Ingresado:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Ingresar Fecha");

        dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        anio.setModel(new javax.swing.SpinnerNumberModel(2017, 2017, 2020, 1));

        jLabel23.setText("Dia:");

        jLabel24.setText("Mes:");

        jLabel25.setText("Anio:");

        ShowMuni1.setText("Municipio 1:");

        ShowMuni2.setText("Municipio 2:");

        ShowMuni3.setText("Municipio 3:");

        ShowMuni4.setText("Municipio 4:");

        ShowMuni5.setText("Municipio 5:");

        ShowMuni6.setText("Municipio 6:");

        ShowMuni7.setText("Municipio 7:");

        ShowMuni8.setText("Municipio 8:");

        ShowMuni9.setText("Municipio 9:");

        ShowMuni10.setText("Municipio 10:");

        Abrir1.setText("Abrir");
        Abrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir1ActionPerformed(evt);
            }
        });

        Cerrar1.setText("Cerrar");
        Cerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar1ActionPerformed(evt);
            }
        });

        Abrir2.setText("Abrir");
        Abrir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir2ActionPerformed(evt);
            }
        });

        Cerrar2.setText("Cerrar");
        Cerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar2ActionPerformed(evt);
            }
        });

        Abrir3.setText("Abrir");
        Abrir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir3ActionPerformed(evt);
            }
        });

        Cerrar3.setText("Cerrar");
        Cerrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar3ActionPerformed(evt);
            }
        });

        Abrir4.setText("Abrir");
        Abrir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir4ActionPerformed(evt);
            }
        });

        Abrir5.setText("Abrir");
        Abrir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir5ActionPerformed(evt);
            }
        });

        Abrir6.setText("Abrir");
        Abrir6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir6ActionPerformed(evt);
            }
        });

        Abrir7.setText("Abrir");
        Abrir7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir7ActionPerformed(evt);
            }
        });

        Abrir8.setText("Abrir");
        Abrir8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir8ActionPerformed(evt);
            }
        });

        Abrir9.setText("Abrir");
        Abrir9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir9ActionPerformed(evt);
            }
        });

        Abrir10.setText("Abrir");
        Abrir10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir10ActionPerformed(evt);
            }
        });

        Cerrar4.setText("Cerrar");
        Cerrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar4ActionPerformed(evt);
            }
        });

        Cerrar5.setText("Cerrar");
        Cerrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar5ActionPerformed(evt);
            }
        });

        Cerrar6.setText("Cerrar");
        Cerrar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar6ActionPerformed(evt);
            }
        });

        Cerrar7.setText("Cerrar");
        Cerrar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar7ActionPerformed(evt);
            }
        });

        Cerrar8.setText("Cerrar");
        Cerrar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar8ActionPerformed(evt);
            }
        });

        Cerrar9.setText("Cerrar");
        Cerrar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar9ActionPerformed(evt);
            }
        });

        Cerrar10.setText("Cerrar");
        Cerrar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar10ActionPerformed(evt);
            }
        });

        Advertencia.setForeground(new java.awt.Color(255, 0, 0));
        Advertencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        RellenarTanque.setText("Rellenar Tanque");
        RellenarTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenarTanqueActionPerformed(evt);
            }
        });

        Utilizar.setText("Utilizar");
        Utilizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtilizarActionPerformed(evt);
            }
        });

        Cambiar.setText("Cambiar Tanque");
        Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo2)
                .addGap(123, 123, 123))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Advertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ShowMuni9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ShowMuni10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir10)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir9)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar9))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel25)
                                        .addGap(6, 6, 6)
                                        .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ShowMuni8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ShowMuni7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ShowMuni6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ShowMuni5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ShowMuni4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ShowMuni3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ShowMuni2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ShowMuni1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir3)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir4)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir5)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir6)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir7)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Abrir8)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cerrar8))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TanquesIngresados, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Utilizar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(RellenarTanque)
                        .addGap(29, 29, 29)
                        .addComponent(Cambiar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanquesIngresados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(Utilizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowMuni1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Abrir1)
                        .addComponent(Cerrar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowMuni2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Abrir2)
                        .addComponent(Cerrar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowMuni3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Abrir3)
                        .addComponent(Cerrar3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowMuni4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Abrir4)
                        .addComponent(Cerrar4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowMuni5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Abrir5)
                        .addComponent(Cerrar5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowMuni6)
                    .addComponent(Cerrar6)
                    .addComponent(Abrir6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowMuni7)
                    .addComponent(Cerrar7)
                    .addComponent(Abrir7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowMuni8)
                    .addComponent(Cerrar8)
                    .addComponent(Abrir8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cerrar9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Abrir9)
                        .addComponent(ShowMuni9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cerrar10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ShowMuni10)
                        .addComponent(Abrir10)))
                .addGap(27, 27, 27)
                .addComponent(Advertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cambiar)
                    .addComponent(RellenarTanque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Consultas");

        MostrarTanques.setText("Mostrar Tanques");
        MostrarTanques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTanquesActionPerformed(evt);
            }
        });

        CalcularCantidadCilindricas.setText("Cantidad de Valvulas en Tanques Cilindricos");
        CalcularCantidadCilindricas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularCantidadCilindricasActionPerformed(evt);
            }
        });

        AguaRegion.setText("Metros Cubicos de agua por Region");
        AguaRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguaRegionActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(MostrarTanques)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(CalcularCantidadCilindricas)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(AguaRegion)
                        .addGap(56, 56, 56))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MostrarTanques)
                .addGap(18, 18, 18)
                .addComponent(CalcularCantidadCilindricas)
                .addGap(18, 18, 18)
                .addComponent(AguaRegion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Acueducto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(543, 543, 543))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTanqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTanqueActionPerformed

    private void FormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormaActionPerformed

    private void IngresarTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarTanqueActionPerformed
        // TODO add your handling code here:
        if ((IDTanque.getText().length())==0||(Municipio1.getText().length()) == 0 || (Municipio2.getText().length()) == 0 || (Municipio3.getText().length()) == 0 || (Municipio4.getText().length()) == 0 || (Municipio5.getText().length()) == 0 || (Municipio6.getText().length()) == 0 || (Municipio7.getText().length()) == 0 || (Municipio8.getText().length()) == 0 || (Municipio9.getText().length()) == 0 || (Municipio10.getText().length()) == 0) {
            JOptionPane.showMessageDialog(null, "No deje campos vacios", "Error", JOptionPane.ERROR_MESSAGE);}
        else{
            int verificacionIngreso = ctrl.buscarTanque2(IDTanque.getText());
            if(verificacionIngreso == 0){
            if(ctrl.getCOntador()<=9){
                String tipo = String.valueOf(Forma.getSelectedItem());
                String id = IDTanque.getText();
                double profundidad = Double.parseDouble(Profundidad.getValue().toString());
                double ancho = Double.parseDouble(Ancho.getValue().toString());
                double radio = Double.parseDouble(Radio.getValue().toString());
                double largo = Double.parseDouble(Largo.getValue().toString());
                String[] mun = new String[10];
                
                mun[0] = Municipio1.getText();

                mun[1] = Municipio2.getText();

                mun[2] = Municipio3.getText();

                mun[3] = Municipio4.getText();

                mun[4] = Municipio5.getText();

                mun[5] = Municipio6.getText();

                mun[6] = Municipio7.getText();

                mun[7] = Municipio8.getText();

                mun[8] = Municipio9.getText();

                mun[9] = Municipio10.getText();
 
                TanquesIngresados.addItem(IDTanque.getText());
                //Tanque ingreso = new Tanque();
                ctrl.crearTanque(tipo, id, profundidad, ancho, radio, largo, mun);
                
                //ingreso.ingresarCapacidad();
                //ctrl.ingresarTanque(ingreso);
                Municipio1.setText("");
                Municipio2.setText("");
                Municipio3.setText("");
                Municipio4.setText("");
                Municipio5.setText("");
                Municipio6.setText("");
                Municipio7.setText("");
                Municipio8.setText("");
                Municipio9.setText("");
                Municipio10.setText("");
                IDTanque.setText("");
                Utilizar.setEnabled(true);
                MostrarTanques.setEnabled(true);
                CalcularCantidadCilindricas.setEnabled(true);
                AguaRegion.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Ingreso realizado con exito", "Ingreso", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Ya no es posible ingresar Tanques", "Error", JOptionPane.ERROR_MESSAGE);  
            }
            }else{
                JOptionPane.showMessageDialog(null, "Ya existe un tanque con dicho ID, intente con otro ID", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_IngresarTanqueActionPerformed

    private void Abrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir1ActionPerformed
        // TODO add your handling code here:
        abrir(0);
        
    }//GEN-LAST:event_Abrir1ActionPerformed

    private void RellenarTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenarTanqueActionPerformed
        // TODO add your handling code here:
        utilizando.rellenarTanque();
        ctrl.reingresarTanque(posicionamiento, utilizando);
        Advertencia.setText("");
        RellenarTanque.setEnabled(false);
        habilitar();
    }//GEN-LAST:event_RellenarTanqueActionPerformed

    private void MostrarTanquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTanquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarTanquesActionPerformed

    private void CalcularCantidadCilindricasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularCantidadCilindricasActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        int cantidad = ctrl.calcularCantidadValvulasCilindricas();
        jTextArea1.setText("La cantidad total de valvulas cilindricas es: "+cantidad);
    }//GEN-LAST:event_CalcularCantidadCilindricasActionPerformed

    private void AguaRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguaRegionActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        double cantidad = ctrl.calcularCantidadAguaTotal();
        jTextArea1.setText("La cantidad de metros cubicos restantes es: "+cantidad);
    }//GEN-LAST:event_AguaRegionActionPerformed

    private void TanquesIngresadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanquesIngresadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanquesIngresadosActionPerformed

    private void UtilizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilizarActionPerformed
        // TODO add your handling code here:
        String ide = TanquesIngresados.getSelectedItem().toString();
        int posicion = ctrl.buscarTanque1(ide);
        Tanque busqueda = ctrl.buscarTanque(ide);
        ShowMuni1.setText("Municipio :"+busqueda.getMunicipioDeValvula(0)); 
        ShowMuni2.setText("Municipio :"+busqueda.getMunicipioDeValvula(1));
        ShowMuni3.setText("Municipio :"+busqueda.getMunicipioDeValvula(2)); 
        ShowMuni4.setText("Municipio :"+busqueda.getMunicipioDeValvula(3)); 
        ShowMuni5.setText("Municipio :"+busqueda.getMunicipioDeValvula(4)); 
        ShowMuni6.setText("Municipio :"+busqueda.getMunicipioDeValvula(5)); 
        ShowMuni7.setText("Municipio :"+busqueda.getMunicipioDeValvula(6)); 
        ShowMuni8.setText("Municipio :"+busqueda.getMunicipioDeValvula(7)); 
        ShowMuni9.setText("Municipio :"+busqueda.getMunicipioDeValvula(8)); 
        ShowMuni10.setText("Municipio :"+busqueda.getMunicipioDeValvula(9));
        utilizando = busqueda;
        posicionamiento = posicion;
        TanquesIngresados.setEnabled(false);
        Utilizar.setEnabled(false);
        habilitar();
    }//GEN-LAST:event_UtilizarActionPerformed

    private void Abrir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir2ActionPerformed
        // TODO add your handling code here:
        abrir(1);
    }//GEN-LAST:event_Abrir2ActionPerformed

    private void Abrir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir3ActionPerformed
        // TODO add your handling code here:
        abrir(2);
    }//GEN-LAST:event_Abrir3ActionPerformed

    private void Abrir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir4ActionPerformed
        // TODO add your handling code here:
        abrir(3);
    }//GEN-LAST:event_Abrir4ActionPerformed

    private void Abrir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir5ActionPerformed
        // TODO add your handling code here:
        abrir(4);
    }//GEN-LAST:event_Abrir5ActionPerformed

    private void Abrir6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir6ActionPerformed
        // TODO add your handling code here:
        abrir(5);
    }//GEN-LAST:event_Abrir6ActionPerformed

    private void Abrir7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir7ActionPerformed
        // TODO add your handling code here:
        abrir(6);
    }//GEN-LAST:event_Abrir7ActionPerformed

    private void Abrir8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir8ActionPerformed
        // TODO add your handling code here:
        abrir(7);
    }//GEN-LAST:event_Abrir8ActionPerformed

    private void Abrir9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir9ActionPerformed
        // TODO add your handling code here:
        abrir(8);
    }//GEN-LAST:event_Abrir9ActionPerformed

    private void Abrir10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir10ActionPerformed
        // TODO add your handling code here:
        abrir(9);
    }//GEN-LAST:event_Abrir10ActionPerformed

    private void CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarActionPerformed
        // TODO add your handling code here:
        Utilizar.setEnabled(true);
        TanquesIngresados.setEnabled(true);
        deshabilitar();
        Utilizar.setEnabled(true);
    }//GEN-LAST:event_CambiarActionPerformed

    private void Cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar1ActionPerformed
        // TODO add your handling code here:
        cerrar(0);
    }//GEN-LAST:event_Cerrar1ActionPerformed

    private void Cerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar2ActionPerformed
        // TODO add your handling code here:
        cerrar(1);
    }//GEN-LAST:event_Cerrar2ActionPerformed

    private void Cerrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar3ActionPerformed
        // TODO add your handling code here:
        cerrar(2);
    }//GEN-LAST:event_Cerrar3ActionPerformed

    private void Cerrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar4ActionPerformed
        // TODO add your handling code here:
        cerrar(3);
    }//GEN-LAST:event_Cerrar4ActionPerformed

    private void Cerrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar5ActionPerformed
        // TODO add your handling code here:
        cerrar(4);
    }//GEN-LAST:event_Cerrar5ActionPerformed

    private void Cerrar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar6ActionPerformed
        // TODO add your handling code here:
        cerrar(5);
    }//GEN-LAST:event_Cerrar6ActionPerformed

    private void Cerrar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar7ActionPerformed
        // TODO add your handling code here:
        cerrar(6);
    }//GEN-LAST:event_Cerrar7ActionPerformed

    private void Cerrar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar8ActionPerformed
        // TODO add your handling code here:
        cerrar(7);
    }//GEN-LAST:event_Cerrar8ActionPerformed

    private void Cerrar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar9ActionPerformed
        // TODO add your handling code here:
        cerrar(8);
    }//GEN-LAST:event_Cerrar9ActionPerformed

    private void Cerrar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar10ActionPerformed
        // TODO add your handling code here:
        cerrar(9);
    }//GEN-LAST:event_Cerrar10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Tanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Tanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Tanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Tanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Tanques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abrir1;
    private javax.swing.JButton Abrir10;
    private javax.swing.JButton Abrir2;
    private javax.swing.JButton Abrir3;
    private javax.swing.JButton Abrir4;
    private javax.swing.JButton Abrir5;
    private javax.swing.JButton Abrir6;
    private javax.swing.JButton Abrir7;
    private javax.swing.JButton Abrir8;
    private javax.swing.JButton Abrir9;
    private javax.swing.JLabel Advertencia;
    private javax.swing.JButton AguaRegion;
    private javax.swing.JSpinner Ancho;
    private javax.swing.JButton CalcularCantidadCilindricas;
    private javax.swing.JButton Cambiar;
    private javax.swing.JButton Cerrar1;
    private javax.swing.JButton Cerrar10;
    private javax.swing.JButton Cerrar2;
    private javax.swing.JButton Cerrar3;
    private javax.swing.JButton Cerrar4;
    private javax.swing.JButton Cerrar5;
    private javax.swing.JButton Cerrar6;
    private javax.swing.JButton Cerrar7;
    private javax.swing.JButton Cerrar8;
    private javax.swing.JButton Cerrar9;
    private javax.swing.JComboBox<String> Forma;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDTanque;
    private javax.swing.JButton IngresarTanque;
    private javax.swing.JSpinner Largo;
    private javax.swing.JButton MostrarTanques;
    private javax.swing.JTextField Municipio1;
    private javax.swing.JTextField Municipio10;
    private javax.swing.JTextField Municipio2;
    private javax.swing.JTextField Municipio3;
    private javax.swing.JTextField Municipio4;
    private javax.swing.JTextField Municipio5;
    private javax.swing.JTextField Municipio6;
    private javax.swing.JTextField Municipio7;
    private javax.swing.JTextField Municipio8;
    private javax.swing.JTextField Municipio9;
    private javax.swing.JSpinner Profundidad;
    private javax.swing.JSpinner Radio;
    private javax.swing.JButton RellenarTanque;
    private javax.swing.JLabel ShowMuni1;
    private javax.swing.JLabel ShowMuni10;
    private javax.swing.JLabel ShowMuni2;
    private javax.swing.JLabel ShowMuni3;
    private javax.swing.JLabel ShowMuni4;
    private javax.swing.JLabel ShowMuni5;
    private javax.swing.JLabel ShowMuni6;
    private javax.swing.JLabel ShowMuni7;
    private javax.swing.JLabel ShowMuni8;
    private javax.swing.JLabel ShowMuni9;
    private javax.swing.JComboBox<String> TanquesIngresados;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JButton Utilizar;
    private javax.swing.JSpinner anio;
    private javax.swing.JSpinner dia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JSpinner mes;
    // End of variables declaration//GEN-END:variables
}
